<BuildResults>
  <myReasonForBuild>
    <myReason>Manual build</myReason>
  </myReasonForBuild>
  <myBuildState>
    <myState>Successful</myState>
  </myBuildState>
  <myBuildErrors>
    <string>Traceback (most recent call last):</string>
    <string>  File &quot;parser.py&quot;, line 165, in &lt;module&gt;</string>
    <string>    shutil.move(retrievedPath, path + &quot;/&quot; + s)</string>
    <string>  File &quot;/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py&quot;, line 291, in move</string>
    <string>    raise Error, &quot;Destination path &apos;%s&apos; already exists&quot; % real_dst</string>
    <string>shutil.Error: Destination path &apos;/Users/wtobey/Desktop/AUITesting/Run 2015-07-17 18:11:14/Community/Community &gt; Ad/Community &gt; Ad at index 20.png&apos; already exists</string>
  </myBuildErrors>
  <myBuildNumber>94</myBuildNumber>
  <myBuildDate>1437156648345</myBuildDate>
  <myBuildDuration>713138</myBuildDuration>
  <mySuccessfulTestResults class="empty-list"/>
</BuildResults>